### ISSUE TITLE
作者老哥你好，请问这个报错是什么原因呢？

### ISSUE THREAD

**Issue by louhuahua** [yuanninesuns/AutoHS#3]
D:\hts1\AutoHS-main>python main.py
Traceback (most recent call last):
  File "D:\hts1\AutoHS-main\main.py", line 1, in <module>
    from FSM_action import system_exit, AutoHS_automata
  File "D:\hts1\AutoHS-main\FSM_action.py", line 7, in <module>
    import click
  File "D:\hts1\AutoHS-main\click.py", line 12, in <module>
    from get_screen import *
  File "D:\hts1\AutoHS-main\get_screen.py", line 6, in <module>
    import win32ui
ImportError: DLL load failed while importing win32ui: 动态链接库(DLL)初始化例程失败。

**Comment by louhuahua** [comment]
解决了，升级pywin
pip install --upgrade pywin32==300 --user

**Comment by yuanninesuns** [comment]
您好！您的邮件已收到，我会尽快查看！祝好
