### ISSUE TITLE
[Solved]這是讀不到卡？

### ISSUE THREAD

**Issue by matsuni373** [yuanninesuns/AutoHS#4]
進選卡畫面就報錯這個
[12:24:26 INFO] Success to truncate Power.log
[12:24:26 DEBUG] 当前状态为：+Leave Hearth Stone
[12:24:26 WARN] HearthStone not found! Try to go back to HS
[12:24:42 INFO] Success to truncate Power.log
[12:24:42 DEBUG] 当前状态为：+Wait main menu
[12:25:12 DEBUG] 当前状态为：+Main Menu
[12:25:22 DEBUG] 当前状态为：+Choosing Hero
[12:25:26 DEBUG] 当前状态为：+Match Opponent
[12:25:37 WARN] my_player_id may be wrong
[12:25:37 DEBUG] 当前状态为：+Choosing Card
Traceback (most recent call last):
  File " AutoHS-main\main.py", line 25, in <module>
    AutoHS_automata()
  File " AutoHS-main\FSM_action.py", line 477, in AutoHS_automata
    FSM_state = FSM_dispatch(FSM_state)
  File " AutoHS-main\FSM_action.py", line 461, in FSM_dispatch
    return dispatch_dict[next_state]()
  File " AutoHS-main\FSM_action.py", line 214, in ChoosingCardAction
    strategy_state = StrategyState(log_state)
  File " AutoHS-main\strategy.py", line 78, in __init__
    self.my_hand_cards.sort(key=lambda temp: temp.zone_pos)
  File " AutoHS-main\strategy.py", line 78, in <lambda>
    self.my_hand_cards.sort(key=lambda temp: temp.zone_pos)
AttributeError: 'NoneType' object has no attribute 'zone_pos'

**Comment by yuanninesuns** [comment]
用的是readme里面的萨满套牌吗

**Comment by matsuni373** [comment]
> 用的是readme里面的萨满套牌吗

知道原因了，介面得是簡體中文
